### ISSUE TITLE
New npm release

### ISSUE THREAD

**Issue by strugee** [SimplyBuilt/hubot-github-issue-lookup#3]
It'd be nice if #1 was released on npm. While I'm at it, it's kinda unfortunate that this isn't 1.x, which is way more useful in terms of semver than 0.x.

**Comment by mjc-gh** [comment]
We can get it released and versions bump Monday. Thanks for pointing this
out!

http://michaeljcoyne.me

**Comment by mjc-gh** [comment]
This is now released here https://www.npmjs.com/package/hubot-github-issue-lookup

**Comment by strugee** [comment]
Thanks! I appreciate it :)
